MoviePro/Controllers/ActorsController.cs
using Microsoft.AspNetCore.Mvc;
using MoviePro.Services.Interfaces;
using System.Threading.Tasks;

namespace MoviePro.Controllers
{
    public class ActorsController : Controller
    {
        private readonly IRemoteMovieService _movieService;
        private readonly IDataMappingService _dataMapping;

        public ActorsController(IRemoteMovieService movieService,
            IDataMappingService dataMapping)
        {
            _movieService = movieService;
            _dataMapping = dataMapping;
        }

        public async Task<IActionResult> Details(int id)
        {
            var actor = await _movieService.ActorDetailAsync(id);
            actor = _dataMapping.MapActorDetail(actor);

            return View(actor);
        }
    }
}

MoviePro/Controllers/MoviesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;
using MoviePro.Data;
using MoviePro.Models.Database;
using MoviePro.Models.Settings;
using MoviePro.Services.Interfaces;
using System.Linq;
using System.Threading.Tasks;

namespace MoviePro.Controllers
{
    public class MoviesController : Controller
    {
        private readonly AppSettings _appSettings;
        private readonly ApplicationDbContext _context;
        private readonly IImageService _imageService;
        private readonly IRemoteMovieService _movieService;
        private readonly IDataMappingService _mappingService;

        public MoviesController(IOptions<AppSettings> appSettings,
            ApplicationDbContext context,
            IImageService imageService,
            IRemoteMovieService movieService,
            IDataMappingService mappingService)
        {
            _appSettings = appSettings.Value;
            _context = context;
            _imageService = imageService;
            _movieService = movieService;
            _mappingService = mappingService;
        }

        public async Task<IActionResult> Index()
        {
            return View();
        }

        public async Task<IActionResult> Import()
        {
            var movies = await _context.Movie.ToListAsync();
            return View(movies);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Import(int id)
        {
            if(_context.Movie.Any(m => m.MovieId == id))
            {
                var localMovie = await _context.Movie.FirstOrDefaultAsync(m => m.MovieId == id);
                return RedirectToAction("Details", "Movies", new { id = localMovie.Id, local = true });
            }

            var movieDetail = await _movieService.MovieDetailAsync(id);
            var movie = await _mappingService.MapMovieDetailAsync(movieDetail);

            _context.Add(movie);
            await _context.SaveChangesAsync();

            await AddToMovieCollection(movie.Id, _appSettings.MovieProSettings.DefaultCollection.Name);

            return RedirectToAction("Inport");
        }

        public async Task<IActionResult> Library()
        {
            var movies = await _context.Movie.ToListAsync();
            return View(movies);
        }

        public IActionResult Create()
        {
            ViewData["CollectionId"] = new SelectList(_context.Collection, "Id", "Name");

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,MovieId,Title,TagLine,Overview,RunTime,ReleaseDate,Rating,VoteAverage,Poster,PosterType,Backdrop,BackdropType,TailerUrl")] Movie movie, int collectionId)
        {
            if (ModelState.IsValid)
            {
                movie.PosterType = movie.PosterFile?.ContentType;
                movie.Poster = await _imageService.EncodeImageAsync(movie.PosterFile);

                movie.BackdropType = movie.BackdropFile?.ContentType;
                movie.Backdrop = await _imageService.EncodeImageAsync(movie.BackdropFile);

                _context.Add(movie);
                await _context.SaveChangesAsync();

                await AddToMovieCollection(movie.Id, collectionId);

                return RedirectToAction("Index", "MovieCollections");
            }

            return View(movie);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _context.Movie.FindAsync(id);
            if (movie == null)
            {
                return NotFound();
            }
            return View(movie);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,MovieId,Title,TagLine,Overview,RunTime,ReleaseDate,Rating,VoteAverage,Poster,PosterType,Backdrop,BackdropType,TailerUrl")] Movie movie)
        {
            if (id != movie.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if(movie.PosterFile != null)
                    {
                        movie.PosterType = movie.PosterFile.ContentType;
                        movie.Poster = await _imageService.EncodeImageAsync(movie.PosterFile);
                    }

                    if (movie.BackdropFile != null)
                    {
                        movie.BackdropType = movie.BackdropFile.ContentType;
                        movie.Backdrop = await _imageService.EncodeImageAsync(movie.BackdropFile);
                    }

                    _context.Update(movie);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MovieExists(movie.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Details", "Movies", new {id = movie.Id, local = true});
            }
            return View(movie);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _context.Movie
                .FirstOrDefaultAsync(m => m.Id == id);
            if (movie == null)
            {
                return NotFound();
            }

            return View(movie);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var movie = await _context.Movie.FindAsync(id);
            _context.Movie.Remove(movie);
            await _context.SaveChangesAsync();
            return RedirectToAction("Library", "Movies");
        }

        private bool MovieExists(int id)
        {
            return _context.Movie.Any(e => e.Id == id);
        }

        public async Task<IActionResult> Details(int? id, bool local = false)
        {
            if(id == null)
            {
                return NotFound();
            }

            Movie movie = new();
            if(local)
            {
                movie = await _context.Movie
                    .Include(m => m.Cast)
                    .Include(m => m.Crew)
                    .FirstOrDefaultAsync(m => m.Id == id);
            }
            else
            {
                var movieDetail = await _movieService.MovieDetailAsync(id.Value);
                movie = await _mappingService.MapMovieDetailAsync(movieDetail);
            }

            if(movie == null)
            {
                return NotFound();
            }

            ViewData["Local"] = local;
            return View(movie);
        }

        private async Task AddToMovieCollection(int movieId, string collectionName)
        {
            var collection = await _context.Collection.FirstOrDefaultAsync(c => c.Name == collectionName);
            _context.Add(
                new MovieCollection()
                {
                    CollectionId = collection.Id,
                    MovieId = movieId
                });

            await _context.SaveChangesAsync();
        }

        private async Task AddToMovieCollection(int movieId, int collcetionId)
        {
            _context.Add(
                new MovieCollection()
                {
                    CollectionId = collcetionId,
                    MovieId = movieId
                });

            await _context.SaveChangesAsync();
        }
    }
}

MoviePro/Views/Movies/Details.cshtml
@using MoviePro.Models.Database

@using MoviePro.Services.Interfaces
@inject IImageService _imageService

@model Movie

<div class="row">
	<div class="col-sm-12 col-md-6">
		<div class="row">
			<img src="@_imageService.DecodeImage(Model.Poster, Model.PosterType)" class="w-100" alt="..." />
		</div>
		<div class="row">
			<button class="btn btn-large btn-block btn-danger font-weight-bold" data-toggle="modal" data-target="#trailer">
				WATCH TRAILER
			</button>
		</div>
	</div>

	<div class="col-sm-12 col-md-6">
		<div class="row">
			<div class="col h5">
				<span class="font-weight-bolder mr-2">TITLE:</span> @Model.Title
			</div>
		</div>

	<hr />

	<div class="row">
		<div class="col h5">
			<span class="font-weight-bolder mr-2">RELEASED:</span> @Model.ReleaseDate.ToString("MMM dd, yyyy")
		</div>
	</div>
	<hr />

	<div class="col h5">
		<div class="row">
			<span class="font-weight-bolder mr-2">RATING:</span> @Model.Rating
		</div>
	</div>
	<hr />

	<div class="col h5">
		<div class="row">
			<span class="font-weight-bolder mr-2">REVIEWS:</span> @Model.VoteAverage
		</div>
	</div>
	<hr />

	<div class="col h5">
		<div class="row">
			<span class="font-weight-bolder">OVERVIEW:</span> @Model.Overview
		</div>
	</div>
		</div>
</div>

<div class="row">
	<div class="col">
		<span class="h5 font-weight-bolder"> STARRING:</span>
	</div>
</div>

@foreach (var actor in Model.Cast.Take(5))
{
	<div class="row">
		<div class="col">
			<div class="card mb-3">
				<div class="row no-gutters">
					<div class="col-md-2">
						<img src="@actor.ImageUrl" class="img-fluid" style="width: 10rem" alt="...">
					</div>
					<div class="col-md-10">
						<div class="card-body">
							<h5 class="card-title">Name:<a asp-action="Details" asp-controller="Actors" asp-route-id="@actor.CastId">@actor.Name</a></h5>
							<p class="card-text">Character: @actor.Character</p>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
}

<div class="modal fade" id="trailer" tabindex="-1" role="dialog" aria-labelledby="trailerLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">@Model.Title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="embed-responsive embed-responsive-16by9">
			@{
				var key = Model.TailerUrl.Split("=").Last();
				var source = $"https://www.youtube.com/embed/{key}";
			}

			<iframe width="560" height="315" src="@source"
				title="YouTube video player" frameborder="0"
				allow="acce;erometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
				allowfullscreen></iframe>
		</div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>